### PR TITLE
Added Debian-10

### LINKED ISSUE #336: Unable to install mysql on debian 10 : No package matching 'mysql-server' is available
Hello,

First thank you for the job done on this role and others roles!

This is the error in the console:
```
TASK [geerlingguy.mysql : Ensure MySQL packages are installed.] ***************************************************************************************************************
fatal: [172.31.2.226]: FAILED! => {"changed": false, "msg": "No package matching 'mysql-server' is available"}
```

### PR DESCRIPTION
**Pull request by pulse-mind**
close #336

### CODE REVIEW

**Comment by GuillaumeGBzh** [comment]
Hi @pulse-mind,

Can you remove the space at the end of the line 8 please ?

**Comment by pulse-mind** [comment]
I will do it next week.

**Comment by pulse-mind** [comment]
I commited the modification on my github, but then how should I do ? Do a new pull request ?

**Comment by GuillaumeGBzh** [comment]
Hi @pulse-mind,

Please revert changes in /vars/Debian.yml. 
This does not work in Ubuntu 1604 (see Travis CI).

**Comment by pulse-mind** [comment]
It is done.
The CI passed on my github.

**Comment by geerlingguy** [comment]
Testing this now, will make a couple different changes to ensure everything's working correctly and simplify the vars includes.

**Pull request closed without merging**
