### PR TITLE
Compatibility for mysqld 5.7 - deprecate config values, handle temporary root password

### PR DESCRIPTION
**Pull request by olenm**
add logic for mysqld 5.7:
- use temporary root password on install
- cli or .my.cnf using password 
deprecate variables not used in mysqld 5.7

tested on COS 7, mysqld version 5.7.11 (https://aws.amazon.com/marketplace/pp/B00UVT5VUO)

### CODE REVIEW

**Comment by olenm** [comment]
appears the tests need to be configured for a centos 7 with mysqld and one with mariadb

Why it is reporting 'mysqld' does not exist in the path for COS6 or should it be hard-coded to /usr/sbin/mysqld for both centos 6 and 7?
Would an absolute path solve this for ubuntu?

**Comment by sbrinkerhoff** [comment]
Is there any plan to merge this into the role?  I've been using olenm's fork to install MySQL, and would prefer to move back to this as my standard.

**Comment by geerlingguy** [comment]
Yes, at some point; since it's not passing the automated tests, it means I'll need to take some time to dig into it before merging, and right now I'm wrapping up a large project and heading off to a week long vacation next week, so I can guarantee it won't happen within 1-2 weeks... but it will happen (at least, MySQL 5.7 will soon be supported).

**Comment by geerlingguy** [comment]
I'm closing this PR in favor of simply getting 5.7.x full support over in https://github.com/geerlingguy/ansible-role-mysql/issues/63. If you'd like to propose MySQL root password handling changes, please submit a separate PR once #63 is complete.

**Pull request closed without merging**
