### PR TITLE
Debian: Mysql 5.6 and higher

### PR DESCRIPTION
**Pull request by olo-dw**
The current mysql package for Debian is 5.5. If you want to install mysql version 5.6 or 5.7 you can use the repo.mysql.com.

I propose this improvement with the readme and the tests.

Btw, I remove an extra services: - docker.

Source: https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/#repo-qg-apt-repo-manual-setup

### CODE REVIEW

**Comment by alexandermeindl** [comment]
This patch looks great. Only think I've concerns is python-mysqldb. This debian package depends on libmysqlclient18, but mysql 5.7 comes with libmysqlclient20. It would be great, if python-mysqldb packages is configurable if to install or not (with __mysql_packages). With this option I can skip  to install python-mysqldb and use pip to get the right MySQL-python version with depends on libmysqlclient20. What do you think about it?

**Comment by geerlingguy** [comment]
This looks great to me, sorry I haven't had time to check into it earlier. Can you rebase since there were some upstream changes to the test structure? I'd also like to make it so you could use the official PPA for Ubuntu, and the yum repos for CentOS (that way no matter what OS, you could either install the system packages or MySQL's official packages).

**Comment by geerlingguy** [comment]
See related for CentOS: https://github.com/geerlingguy/ansible-role-mysql/issues/73

**Comment by olo-dw** [comment]
Rebase done.

**Pull request closed without merging**
