### PR TITLE
Disable Starting of MySQL on Debian during install.

### PR DESCRIPTION
**Pull request by misilot**
Disable Starting of MySQL Server on Debian based systems during install.

### CODE REVIEW

**Comment by misilot** [comment]
not stale

**Comment by misilot** [comment]
not stale

**Comment by geerlingguy** [comment]
I like this idea, but for some reason tests aren't running on this PR...?

**Comment by misilot** [comment]
Let me rebase and see what happens

**Comment by JoyceBabu** [comment]
I am trying to install MariaDB 10.8 with this role by adding the mariadb repository for the version using a pre task. But the role is failing when running task [Ensure MySQL is started and enabled on boot](https://github.com/geerlingguy/ansible-role-mysql/blob/master/tasks/configure.yml#L85) since the default `ib_logfile0` was deleted by the role after installation.

> [ERROR] InnoDB: File ./ib_logfile0 was not found

Will this PR fix the issue?

**Comment by johansenha** [comment]
> I am trying to install MariaDB 10.8 with this role by adding the mariadb repository for the version using a pre task. But the role is failing when running task [Ensure MySQL is started and enabled on boot](https://github.com/geerlingguy/ansible-role-mysql/blob/master/tasks/configure.yml#L85) since the default `ib_logfile0` was deleted by the role after installation.
> 
> > [ERROR] InnoDB: File ./ib_logfile0 was not found
> 
> Will this PR fix the issue?

same happening to me. Mariadb 10.8 on ubuntu22.04.01

**Comment by misilot** [comment]
Thanks @geerlingguy!

**Pull request merged**
