### PR TITLE
Disallow remote mysql root connections

### PR DESCRIPTION
**Pull request by kostyrevaa**
This PR adds feature to disallow remote mysql root connections so we can fight mysql root brutforcing.

### CODE REVIEW

**Comment by kostyrevaa** [comment]
Up

**Comment by geerlingguy** [comment]
@kostyrevaa - Sorry about not taking a look at this sooner—this is definitely something I want to add; I've merged the similar change from #75, which is a little more secure in the way it handles the deletion (since the fqdn might be different than what's in the database already).

**Comment by kostyrevaa** [comment]
yeah.
It took you six months.
Fortunately for me I use mysql no longer.

**Comment by geerlingguy** [comment]
@kostyrevaa - Sorry about the delay, but I'm glad you're using something that suits your needs now!

**Pull request closed without merging**
