### PR TITLE
Support MySQL 5.7 temporary random root password

### PR DESCRIPTION
**Pull request by trevorr**
Fixes merge conflict in #237 and adds minor tweaks

### CODE REVIEW

**Comment by broferek** [comment]
Would really love this to be merged as I need to fork the role for the moment

I have tested it on Centos 7.5 and mysql 5.7.22 and it works perfectly

**Comment by trevorr** [comment]
And I've tested it on CentOS 6.9.

**Comment by geerlingguy** [comment]
@cinject - mostly because I've been in and out of the hospital all year :)

I'll get to reviewing it at some point. @trevorr can you give more background to the reasoning for the changes, why it's necessary, etc?

**Comment by trevorr** [comment]
@geerlingguy Sorry to hear about the hospitalization.

The background for this PR is that MySQL 5.7 community edition cannot be automatically installed with a known root password. The install process generates a random temporary root password that only appears in the log. This PR takes the approach of extracting the temporary password from the log and changing it to a user-requested password.

Another alternative would be patching the SysV startup script. While the server itself has the ability not to use a random password initially, the startup script is hard-coded to use one. I imagine the various Linux distribution packages take this approach, but it seems fragile for an Ansible script.

**Comment by lwm** [comment]
A much needed change. Looks good to me.

**Comment by lwm** [comment]
I ran a test over this for idempotency, and I think it needs some tweaks:

```
ERROR: Idempotence test failed because of the following tasks:
* [instance] => role : Acquire temporary root password
* [instance] => role : Copy .my.cnf file with temporary root password credentials
* [instance] => role : Overwrite .my.cnf file with root password credentials
```

**Comment by broferek** [comment]
@geerlingguy Any chance this PR can be merged? I still have a fork for this and am fighting to get regular updates of the role because of that.
I'm working with this fork for all my Mysql installs since several months now and it works very well.

**Comment by geerlingguy** [comment]
Can you rebase on the current master branch? I want to make sure molecule idempotence tests pass, based on @lwm's review above; they are present in the latest master commit.

**Comment by trevorr** [comment]
I rebased and fixed a new lint indentation error. I think the tests pass, except that one out of five timed out. Is there a way to rerun it without pushing again?

**Comment by geerlingguy** [comment]
Triggered a new run on that failed job.

**Comment by trevorr** [comment]
Same failure with Ubuntu 16.04:

```
 TASK [geerlingguy.mysql : Ensure MySQL Python libraries are installed.] ********
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by ktibi** [comment]
We need this feature !

**Comment by lksnmnn** [comment]
Is there a reason why this was never merged? My idempotence tests are failing when rewriting the initial root password using this flag:

```
    mysql_root_password_update: yes
```

**Comment by hectoralicea** [comment]
any update on this?  I'm getting this build error due to this issue with mysql57

```
TASK [geerlingguy.mysql : Disallow root login remotely] ******************************************************************************************************************
failed: [172.25.91.140] (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')) => changed=false 
  ansible_loop_var: item
  cmd:
  - mysql
  - -NBe
  - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  delta: '0:00:00.008352'
  end: '2021-08-20 12:30:03.177413'
  item: DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  msg: non-zero return code
  rc: 1
  start: '2021-08-20 12:30:03.169061'
  stderr: 'ERROR 1045 (28000): Access denied for user ''root''@''localhost'' (using password: NO)'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

**Pull request closed without merging**
