### PR TITLE
Allow mysql_mode to be set to the empty string

### PR DESCRIPTION
**Pull request by nkakouros**
This is similar to #227 and #229.

According to the [documentation](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_sql_mode), the default for `sql_mode` is **not to be empty**. If someone wants to set it to empty, it is impossible with this role. This PR changes that so that it becomes possible.

I run a custom CMS (not publicly available) that needs that expects that option to be set to empty. 

The PR is minimal and not additional maintenance overhead is added.

### CODE REVIEW

**Comment by nkakouros** [comment]
Hope dies last.

**Comment by nkakouros** [comment]
I wonder what it means to run stalebot if there is no engagement by the maintainer. My conclusion is that contributions are not welcome.

**Comment by nkakouros** [comment]
@geerlingguy Could you review this?

**Comment by nkakouros** [comment]
@geerlingguy Could you check this tiny, tiny PR?

**Comment by nkakouros** [comment]
@geerlingguy Are you alive and well?

**Comment by nkakouros** [comment]
😂 🥳 🎉 🎆

**Comment by geerlingguy** [comment]
@nkakouros 😂

Persistence pays off!

**Pull request merged**
