### PR TITLE
Add TLS settings to mysql.cnf

### PR DESCRIPTION
**Pull request by tmgstevens**
Add additional settings for TLS/SSL configuration into mysql.cnf (reference: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.htm)

### CODE REVIEW

**Comment by hectoralicea** [comment]
this looks like a very good idea especially in agencies that are getting dinged for having software that support TLS 1.1 encryption

**Comment by tmgstevens** [comment]
Can we get a commit on this please?

**Comment by tmgstevens** [comment]
Please could you commit this @geerlingguy ?

**Comment by tmgstevens** [comment]
This is still relevant - can we get a merge please?

**Pull request closed without merging**
