### PR TITLE
Set the min/max word characters in search indexes

### PR DESCRIPTION
**Pull request by bhean**
Hi!

This is a very small modification to allow to set a pair of "fulltext" options: min and max characters in a indexed word (https://dev.mysql.com/doc/refman/5.7/en/fulltext-fine-tuning.html)

This Ansible-role is very nice, and with this small modification it will be very usefull for me!

Thank you!

### CODE REVIEW

**Comment by bhean** [comment]
Now the values are for MyISAM tables... 
In the InnoDB tables you need MySQL >= 5.6, so I removed these settings by the moment

**Comment by bhean** [comment]
@geerlingguy, I opened this PR 2 years ago... please, can you take a look? I think its a good improve, IMHO...

**Comment by geerlingguy** [comment]
These options don't fit what I'd consider the 80% use case for this role and are not used in many installations. In this case, I'd suggest copying the my.cnf.j2 template into your playbook and customizing it as you see fit, and managing it via your playbook (setting `overwrite_global_mycnf: true` to `false` so this role doesn't change that file).

**Comment by bhean** [comment]
These optiones are completely optional... you can use if you need it, and you can NOT if you don't need it (like in the 80% use case that you mention) because the default values setted in the config are the default values of the official MySQL installation. I think this PR extends the features of the role without any "breaking change" and without increase complexity... but its ok. Thanks.

**Comment by geerlingguy** [comment]
@bhean - I understand, but every additional variable added is another variable which _should be_ (but often isn't) tested independently, and which (and this has happened in the past 5 years of this role's maintenance) could be deprecated or renamed in a future MySQL version, which would mean that variable would need to be redone in a backwards-compatible shim.

It's easier to take a 'less is more' approach in this role, and allow users to override the configuration on their own for more esoteric variables (IMO).

**Pull request closed without merging**
