### PR TITLE
Remove shell-module touch in mysql role, use file-module instead.

### PR DESCRIPTION
**Pull request by rpsu**
#150

### CODE REVIEW

**Comment by geerlingguy** [comment]
It looks like this breaks idempotence:

```
TASK [role_under_test : Create error log file (if configured).] ****************
changed: [localhost]
```

**Comment by geerlingguy** [comment]
The task would need a `changed_when: false` added (as per https://github.com/ansible/ansible/issues/7490#issuecomment-154117597). See also: https://github.com/ansible/ansible-modules-core/issues/170

**Comment by jp1987** [comment]
Maybe add a warn=no instead then?

**Comment by geerlingguy** [comment]
@jp1987 - Yeah, that could work.

**Comment by geerlingguy** [comment]
Fixed in https://github.com/geerlingguy/ansible-role-mysql/commit/f45e1a892ce13eeadda434d028915b40db0db29a

**Pull request closed without merging**
