### PR TITLE
MariaDB support

### PR DESCRIPTION
**Pull request by abelboldu**

### CODE REVIEW

**Comment by abelboldu** [comment]
bump

**Comment by geerlingguy** [comment]
For the packages list—is that for CentOS, Ubuntu, or what OS? I think it would be best if we can add in the README an example for at least each of the major platforms (with default/starting point of CentOS 7).

**Comment by JorisVanEijden** [comment]
:+1: I'm now using this on my CentOS7 machines.

**Comment by abelboldu** [comment]
Sorry for the long wait.

Yes, I tested it on Centos 7 machines.

Will try will ubuntu14 shortly

**Comment by geerlingguy** [comment]
@abelboldu - Thanks! If you can give an example list for Ubuntu 14.04, that's good enough for me, and I'll definitely merge ASAP.

**Comment by abelboldu** [comment]
Done.

**Comment by geerlingguy** [comment]
@abelboldu - to be extra clear; the other variables still need to be set correctly for Ubuntu, correct? (All the other changes besides the packages).

**Comment by abelboldu** [comment]
No,  the ubuntu example works as described in the example,  no extra variables need to be set. 

El 18 de junio de 2015 18:38:24 CEST, Jeff Geerling <notifications@github.com> escribió:
>@abelboldu - to be extra clear; the other variables still need to be
>set correctly for Ubuntu, correct? (All the other changes besides the
>packages).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/geerlingguy/ansible-role-mysql/pull/38#issuecomment-113212822

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by geerlingguy** [comment]
Thanks! Merged, and I'll be testing and tweaking to make sure the docs are up to snuff and work on all environments just as well as before.

**Pull request merged**
